//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wizbuotomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analiz
    {
        public int id { get; set; }
        public Nullable<int> Gorevid { get; set; }
        public Nullable<int> Sure { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Gorev_Personel Gorev_Personel { get; set; }
    }
}
