//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wizbuotomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorevler
    {
        public Gorevler()
        {
            this.Gorev_Personel = new HashSet<Gorev_Personel>();
        }
    
        public int Id { get; set; }
        public string Gorev { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Sure { get; set; }
    
        public virtual ICollection<Gorev_Personel> Gorev_Personel { get; set; }
    }
}
