//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wizbuotomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorev_Personel
    {
        public Gorev_Personel()
        {
            this.Analiz = new HashSet<Analiz>();
        }
    
        public int Id { get; set; }
        public int Personel { get; set; }
        public int Gorev { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public string Durum { get; set; }
        public string Aciklama { get; set; }
    
        public virtual ICollection<Analiz> Analiz { get; set; }
        public virtual Gorevler Gorevler { get; set; }
        public virtual Personel Personel1 { get; set; }
    }
}
