//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wizbuotomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public Personel()
        {
            this.Gorev_Personel = new HashSet<Gorev_Personel>();
        }
    
        public int Id { get; set; }
        public string Adi_Soyadi { get; set; }
        public string Sifre { get; set; }
        public string Adres { get; set; }
        public Nullable<int> BildigiDiller { get; set; }
        public string Okulu { get; set; }
        public string Kullaniciadi { get; set; }
    
        public virtual BildigiDiller BildigiDiller1 { get; set; }
        public virtual ICollection<Gorev_Personel> Gorev_Personel { get; set; }
    }
}
