//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wizbuotomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yapilan
    {
        public int Id { get; set; }
        public Nullable<int> GorevId { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public Nullable<int> Sure { get; set; }
        public string Yapilan1 { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
